FROM php:7.2-apache

RUN apt-get update &&  apt-get install -y zlib1g-dev curl  git vim  
#RUN rm -rf /var/lib/apt/lists/* 
    

RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli
RUN docker-php-ext-install zip 

RUN curl --insecure https://getcomposer.org/composer.phar -o /usr/bin/composer && chmod +x /usr/bin/composer
COPY config/php.ini /usr/local/etc/php/
